before_script:
  - git lfs pull


stages:
    - test
    - deploy


test_enpt:
  stage: test
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  script:
    - pixi install -e dev
    # - pixi list --fields name,version,build,kind
    - pixi run -e dev pytest
    - pixi run -e dev docs
  artifacts:
    expose_as: 'Test and coverage report'
    paths:
    - htmlcov/
    - report.html
    - docs/_build/html/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

    expire_in: 30 days
    when: always


test_styles:
  stage: test
  script:
    - pixi install -e lint
    - pixi run -e lint lint


test_urls:
  stage: test
  script:
    - pixi install -e urlcheck
    - pixi run -e urlcheck urlcheck
  when: always


test_enpt_install:
  stage: test
  script:
    - git lfs pull

    # create a fresh pixi environment from pyproject.toml and install the package
    - pixi install

    # check if the dependencies are installed correctly
    - pixi run pip check || true

    # import test
    - cd ..
    - ls
    - pixi run -m EnPT/pyproject.toml python -c "import enpt; print(enpt)"
    - pixi run -m EnPT/pyproject.toml python -c "from enpt.model.images import EnMAPL1Product_SensorGeo"
  only:
    - main
    - dev


pages:
  stage: deploy
  dependencies:
    - test_enpt
  script:
    # Create the public directory
    - rm -rf public
    - mkdir public
    - mkdir -p public/doc
    - mkdir -p public/img
    - mkdir -p public/coverage
    - mkdir -p public/test_reports

    # Copy over the docs
    - cp -r docs/_build/html/* public/doc/
    - cp -r docs/img/* public/img/

    # Copy over the coverage reports
    - cp -r htmlcov/* public/coverage/

    # Copy over the test reports
    - cp report.html public/test_reports/

    # Check if everything is working great
    - ls -al public
    - ls -al public/doc
    - ls -al public/coverage
    - ls -al public/test_reports
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - main
    - enhancement/improve_docs


deploy_pypi:
  stage: deploy
  dependencies:
    - test_enpt
  script:
    - pixi install -e deploy
    - pixi run -e deploy python -m build --sdist
    - pixi run -e deploy twine check dist/*
    - pixi run -e deploy twine upload dist/*  # requires creds as environment variables
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - dev


create_github_release:
    stage: deploy
    dependencies:
        - test_enpt
    script:
        - bash ./.github/create_release_from_gitlab_ci.sh  # uses environment variables set in the UI
    only:
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    except:
        - dev


gitleaks: # Gitleaks security scanner
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  stage: test
  before_script: []  # prevents git lfs pull
  script:
    - gitleaks git --platform gitlab --max-decode-depth 5 --verbose --redact $CI_PROJECT_DIR
